[package]
name = "message_dapp"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
pwr-rs = { path = "/Users/khairallah/Desktop/Projects/pwrlabs/os/pwrrs" }
serde_json = "1.0.128"
tokio = { version = "1.0", features = ["full"] }
